version: '3.8'

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    network_mode: host

  strapi:
    image: node:20
    working_dir: /srv/app
    command: bash -c "npm install && npm run develop"
    volumes:
      - ./:/srv/app
    # ports:
    #   - "1337:1337"
    depends_on:
      - db
    network_mode: host

volumes:
  db-data:
